export const images = [
    {src: './assets/fotoMalu2.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu20.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu19.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu18.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu17.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu16.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu15.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu14.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu13.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu12.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu11.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu10.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu9.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu8.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu7.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu6.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu5.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu4.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu3.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu1.jpeg', alt: 'eu te amo', wide : true},
    {src: './assets/fotoMalu.jpeg', alt: 'eu te amo', wide : true},
]